[versions]
agp = "8.13.2"
androidxCoreKtx = "1.12.0"
appcompatVersion = "1.7.0"
coreKtxVersion = "1.13.1"
kotlin = "2.0.21"
coreKtx = "1.17.0"
junit = "4.13.2"
junitVersion = "1.3.0"
espressoCore = "3.7.0"
appcompat = "1.7.1"
lifecycleViewmodelKtx = "2.10.0"
material = "1.13.0"
activity = "1.12.1"
constraintlayout = "2.2.1"
materialVersion = "1.11.0"
mpandroidchart = "v3.1.0"
osmdroidAndroid = "6.1.20"
osmdroidAndroidVersion = "6.1.14"
osmdroidOsmdroidAndroid = "6.1.18"
playServicesLocation = "21.3.0"
retrofit = "3.0.0"
roomRuntimeVersion = "2.8.4"

[libraries]
androidx-appcompat-v170 = { module = "androidx.appcompat:appcompat", version.ref = "appcompatVersion" }
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "coreKtx" }
androidx-core-ktx-v1120 = { module = "androidx.core:core-ktx", version.ref = "androidxCoreKtx" }
androidx-core-ktx-v1131 = { module = "androidx.core:core-ktx", version.ref = "coreKtxVersion" }
androidx-lifecycle-viewmodel-ktx = { module = "androidx.lifecycle:lifecycle-viewmodel-ktx", version.ref = "lifecycleViewmodelKtx" }
androidx-room-compiler = { module = "androidx.room:room-compiler", version.ref = "roomRuntimeVersion" }
converter-gson = { module = "com.squareup.retrofit2:converter-gson", version.ref = "retrofit" }
junit = { group = "junit", name = "junit", version.ref = "junit" }
androidx-junit = { group = "androidx.test.ext", name = "junit", version.ref = "junitVersion" }
androidx-espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espressoCore" }
androidx-appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
material = { group = "com.google.android.material", name = "material", version.ref = "material" }
androidx-activity = { group = "androidx.activity", name = "activity", version.ref = "activity" }
androidx-constraintlayout = { group = "androidx.constraintlayout", name = "constraintlayout", version.ref = "constraintlayout" }
material-v1110 = { module = "com.google.android.material:material", version.ref = "materialVersion" }
mpandroidchart = { module = "com.github.PhilJay:MPAndroidChart", version.ref = "mpandroidchart" }
osmdroid-android = { module = "org.osmdroid:osmdroid-android", version.ref = "osmdroidAndroid" }
osmdroid-android-v6114 = { module = "org.osmdroid:osmdroid-android", version.ref = "osmdroidAndroidVersion" }
osmdroid-android-v6118 = { module = "org.osmdroid:osmdroid-android", version.ref = "osmdroidOsmdroidAndroid" }
osmdroid-wms = { module = "org.osmdroid:osmdroid-wms", version.ref = "osmdroidAndroidVersion" }
play-services-location = { group = "com.google.android.gms", name = "play-services-location", version.ref = "playServicesLocation" }
retrofit = { module = "com.squareup.retrofit2:retrofit", version.ref = "retrofit" }
room-ktx = { module = "androidx.room:room-ktx", version.ref = "roomRuntimeVersion" }
room-runtime = { module = "androidx.room:room-runtime", version.ref = "roomRuntimeVersion" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }

